version: '3.8'

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db/demo_app_production
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db/demo_app_production
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
