version: '3.8'

services:
  web:
    build: .
    command: bash -c "bundle exec rails db:create db:migrate RAILS_ENV=production"
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db/demo_app_production
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy   # Wait for the database service to become healthy before starting the web service

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo_app_production
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5

volumes:
  db_data:
    driver: local
